name: wizepair-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - boost=1.74.0
  - boost-cpp=1.74.0
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - cairo=1.16.0
  - certifi=2020.6.20
  - decorator=4.4.2
  - fontconfig=2.13.1
  - freetype=2.10.2
  - gettext=0.19.8.1
  - glib=2.66.1
  - icu=67.1
  - ipykernel=5.3.4
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - jpeg=9d
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - lcms2=2.11
  - ld_impl_linux-64=2.35
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.8.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - ncurses=6.2
  - numpy=1.19.1
  - olefile=0.46
  - openssl=1.1.1h
  - pandas=1.1.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2.3
  - pixman=0.38.0
  - prompt_toolkit=1.0.15
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycairo=1.19.1
  - pygments=2.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6=1_cp36m
  - pytz=2020.1
  - pyzmq=19.0.2
  - rdkit=2020.03.6
  - readline=8.0
  - setuptools=49.6.0
  - simplegeneric=0.8.1
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.2.5
  - wheel=0.35.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zeromq=4.3.3
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - networkx==2.5
